spring:
    datasource:
        password: 
        url: jdbc:h2:mem:testdb
        username: sa
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
            
google:
    key: ${GOOGLEKEY}
    geocode-url: https://maps.googleapis.com/maps/api/geocode/json
        