spring:
    datasource:
        password: 
        url: jdbc:h2:mem:testdb
        username: sa
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
            
google:
    key: ${GOOGLEKEY}
    geocode-url: https://maps.googleapis.com/maps/api/geocode/json
    direction-url: https://maps.googleapis.com/maps/api/directions/json
    maps-url: https://www.google.com/maps/dir/
    origin: ChIJ2_2GVtjvzJQRuGJfRNGhwis
    destination: ChIJ2_2GVtjvzJQRuGJfRNGhwis
        