INSERT INTO DOADOR (nome, contato, rua, bairro, numero) VALUES ('Fabio', null, 'Avenida Monsenhor João José de Azevedo', 'Crispim', '181')
INSERT INTO DOADOR (nome, contato, rua, bairro, numero) VALUES ('Bianca', null, 'Rua Amadeu Ribeiro', 'Andrade', '81')
INSERT INTO DOADOR (nome, contato, rua, bairro, numero) VALUES ('Izabel', null, 'Augustin San Martin', 'Crispim', '260')
INSERT INTO DOADOR (nome, contato, rua, bairro, numero) VALUES ('Eduardo', null, 'Rua Vitório Bassos', 'Parque São Domingos', '181')
INSERT INTO DOADOR (nome, contato, rua, bairro, numero) VALUES ('Pablo', null, 'Rua Xyz', 'Crispim', '233')
INSERT INTO DOADOR (nome, contato, rua, bairro, numero) VALUES ('Marcílio', null, 'Rua 3', 'Crispim', '1')